// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FrontendRequestController from "./frontend_request_controller"
application.register("frontend-request", FrontendRequestController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalOpenerController from "./modal_opener_controller"
application.register("modal-opener", ModalOpenerController)

import NavigationMenuController from "./navigation_menu_controller"
application.register("navigation-menu", NavigationMenuController)

import ResourcePickerController from "./resource_picker_controller"
application.register("resource-picker", ResourcePickerController)
