inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false
  
Style/ClassMethodsDefinitions:
  Enabled: false